AllCops:
  TargetRubyVersion: 2.4

inherit_gem:
  rubocop_defaults: .rubocop.yml

inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
  - Exclude

Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/compendium/abstract_chart_provider.rb'

RSpec/ExampleLength:
  Max: 10

Style/DateTime:
  Exclude:
    - 'spec/compendium/param_types/date_spec.rb'

Style/FormatString:
  EnforcedStyle: sprintf

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/IfUnlessModifier:
  Exclude:
    - 'Gemfile'

Style/MethodMissingSuper:
  Exclude:
    - 'lib/compendium/presenters/settings/query.rb'

Style/RescueModifier:
  Enabled: false

Style/SymbolArray:
  MinSize: 3
