sudo: false
language: ruby
cache:
  - bundler
rvm:
  - 2.2.9
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - 2.7.0.preview1
gemfile:
  - .travis/gemfiles/rails3.gemfile
  - .travis/gemfiles/rails4.gemfile
  - .travis/gemfiles/rails5.gemfile
  - .travis/gemfiles/rails6.gemfile
matrix:
  exclude:
    - rvm: 2.2.9
      gemfile: .travis/gemfiles/rails6.gemfile
    - rvm: 2.3.8
      gemfile: .travis/gemfiles/rails6.gemfile
    - rvm: 2.4.6
      gemfile: .travis/gemfiles/rails6.gemfile
    - rvm: 2.7.0.preview1
      gemfile: .travis/gemfiles/rails3.gemfile
    - rvm: 2.7.0.preview1
      gemfile: .travis/gemfiles/rails4.gemfile
  allow_failures:
    - rvm: 2.7.0.preview1
