sudo: false
language: ruby
cache:
  bundler: true
  directories: $HOME/.cache/rubocop_cache
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7.0.preview1
gemfile:
  - .travis/gemfiles/rails3.gemfile
  - .travis/gemfiles/rails4.gemfile
  - .travis/gemfiles/rails5.gemfile
  - .travis/gemfiles/rails6.gemfile
matrix:
  exclude:
    - rvm: 2.2
      gemfile: .travis/gemfiles/rails6.gemfile
    - rvm: 2.3
      gemfile: .travis/gemfiles/rails6.gemfile
    - rvm: 2.4
      gemfile: .travis/gemfiles/rails6.gemfile
    - rvm: 2.7.0.preview1
      gemfile: .travis/gemfiles/rails3.gemfile
    - rvm: 2.7.0.preview1
      gemfile: .travis/gemfiles/rails4.gemfile
  allow_failures:
    - rvm: 2.7.0.preview1
jobs:
  include:
    - stage: rubocop
      rvm: 2.6
      gemfile: Gemfile
      script: bundle exec rubocop
stages:
  - rubocop
  - test
